print("Welcome to the Letter Counter")
print()
first_name = input("Please enter your first name: ")
print()
print("Hello " + first_name.title())
print()
print("This program will display the number of occurences a letter appears in a message.")
print()
message = input("Please enter the message you would like to use: ")
print()
chosen_letter = input("Please enter the letter you would like to count: ")
print()
message = message.lower()
chosen_letter = chosen_letter.lower()
letter_count = message.count(chosen_letter)
print(first_name.title() + ", your chosen letter occured " + str(letter_count) + " times.")

